# Generated by Django 5.1.15 on 2026-09-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
