# Generated by Django 5.1.15 on 2026-09-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('UNDER_OFFER', 'Under Offer'), ('SOLD', 'Sold'), ('RENTED', 'Rented'), ('INACTIVE', 'Inactive'), ('PENDING_APPROVAL', 'Pending Approval')], default='ACTIVE', max_length=20),
        ),
    ]
