# Generated by Django 5.1.15 on 2026-09-04 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField(blank=True)),
                ('preferred_visit_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New Inquiry'), ('CONTACTED', 'Contacted'), ('SITE_VISIT', 'Site Visit Scheduled'), ('NEGOTIATION', 'In Negotiation'), ('CLOSED', 'Closed / Deal Won'), ('LOST', 'Lost / Dropped')], default='NEW', max_length=20)),
                ('agent_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='properties.property')),
            ],
            options={
                'verbose_name_plural': 'Property Inquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='properties__status_773da0_idx'), models.Index(fields=['created_at'], name='properties__created_4a4c61_idx')],
            },
        ),
    ]
