from django.urls import path
from .views import (
    PropertyListCreateView,
    PropertyDetailView,
    PropertyRadiusSearchView,
    PropertyPolygonSearchView,
    PropertyBoundingBoxSearchView,
    PropertyNearestAmenitiesView,
    PropertyLocationScoreView,
    AgentInventoryAPIView,
    PropertyImageUploadView,
    PropertyImageDetailView,
    PropertyInquiryCreateView,
    AgentLeadsAPIView,
    AgentLeadDetailView,
    PropertyCompareAPIView,
)
from .admin_views import (
    AdminModerationStatsAPIView,
    AdminPropertyListAPIView,
    AdminPropertyDecisionAPIView,
    AdminPropertyBulkDecisionAPIView,
    AdminAgentListAPIView,
    AdminAgentVerifyAPIView,
    AdminUserListAPIView,
    AdminUserDetailAPIView,
    AdminUserBulkActionAPIView,
    AdminAmenityListAPIView,
    AdminAmenityDetailAPIView,
    AdminAreaListAPIView,
)

app_name = 'properties'

urlpatterns = [
    path('', PropertyListCreateView.as_view(), name='property_list_create'),
    path('admin/moderation/stats/', AdminModerationStatsAPIView.as_view(), name='admin_moderation_stats'),
    path('admin/moderation/properties/', AdminPropertyListAPIView.as_view(), name='admin_moderation_properties'),
    path('admin/moderation/properties/bulk-decision/', AdminPropertyBulkDecisionAPIView.as_view(), name='admin_moderation_property_bulk'),
    path('admin/moderation/properties/<int:pk>/decision/', AdminPropertyDecisionAPIView.as_view(), name='admin_moderation_decision'),
    path('admin/moderation/agents/', AdminAgentListAPIView.as_view(), name='admin_moderation_agents'),
    path('admin/moderation/agents/<int:pk>/verify/', AdminAgentVerifyAPIView.as_view(), name='admin_moderation_agent_verify'),
    path('admin/moderation/users/', AdminUserListAPIView.as_view(), name='admin_moderation_users'),
    path('admin/moderation/users/bulk-action/', AdminUserBulkActionAPIView.as_view(), name='admin_moderation_user_bulk'),
    path('admin/moderation/users/<int:pk>/', AdminUserDetailAPIView.as_view(), name='admin_moderation_user_detail'),
    path('admin/moderation/amenities/', AdminAmenityListAPIView.as_view(), name='admin_moderation_amenities'),
    path('admin/moderation/amenities/<int:pk>/', AdminAmenityDetailAPIView.as_view(), name='admin_moderation_amenity_detail'),
    path('admin/moderation/areas/', AdminAreaListAPIView.as_view(), name='admin_moderation_areas'),
    path('inventory/', AgentInventoryAPIView.as_view(), name='property_inventory_api'),
    path('leads/', AgentLeadsAPIView.as_view(), name='agent_leads_api'),
    path('leads/<int:pk>/', AgentLeadDetailView.as_view(), name='agent_lead_detail'),
    path('<int:pk>/', PropertyDetailView.as_view(), name='property_detail'),
    path('<int:pk>/inquire/', PropertyInquiryCreateView.as_view(), name='property_inquire'),
    path('<int:pk>/images/', PropertyImageUploadView.as_view(), name='property_image_upload'),
    path('<int:pk>/images/<int:image_id>/', PropertyImageDetailView.as_view(), name='property_image_detail'),
    path('<int:pk>/nearest-amenities/', PropertyNearestAmenitiesView.as_view(), name='property_nearest_amenities'),
    path('<int:pk>/location-score/', PropertyLocationScoreView.as_view(), name='property_location_score'),
    path('radius-search/', PropertyRadiusSearchView.as_view(), name='property_radius_search'),
    path('polygon-search/', PropertyPolygonSearchView.as_view(), name='property_polygon_search'),
    path('bbox-search/', PropertyBoundingBoxSearchView.as_view(), name='property_bbox_search'),
    path('compare/', PropertyCompareAPIView.as_view(), name='property_compare'),
]

